from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from train_models import (
    build_models,
    load_modeling_data,
    split_features_target,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]

REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

COEFFICIENTS_PATH = REPORTS_DIR / "ridge_feature_coefficients.csv"

INTERPRETATION_MODEL_NAME = "ridge_regression"


def clean_feature_name(feature_name: str) -> str:
    """
    Clean feature names generated by ColumnTransformer and OneHotEncoder.
    """
    prefixes = [
        "numeric_zero__",
        "numeric_median__",
        "categorical_none__",
        "categorical_most_frequent__",
    ]

    cleaned_name = feature_name

    for prefix in prefixes:
        cleaned_name = cleaned_name.replace(prefix, "")

    return cleaned_name


def infer_feature_group(feature_name: str) -> str:
    """
    Infer feature group from transformed feature name.
    """
    if feature_name.startswith("numeric_zero__"):
        return "numeric_zero"
    if feature_name.startswith("numeric_median__"):
        return "numeric_median"
    if feature_name.startswith("categorical_none__"):
        return "categorical_none"
    if feature_name.startswith("categorical_most_frequent__"):
        return "categorical_most_frequent"

    return "unknown"


def train_interpretation_model() -> tuple[object, pd.DataFrame]:
    """
    Train Ridge regression for coefficient-based interpretation.
    """
    train_data, validation_data, feature_groups = load_modeling_data()

    (
        X_train,
        _,
        y_train_log,
        _,
        _,
        _,
    ) = split_features_target(
        train_data=train_data,
        validation_data=validation_data,
        feature_groups=feature_groups,
    )

    models = build_models(feature_groups)
    ridge_model = models[INTERPRETATION_MODEL_NAME]

    ridge_model.fit(X_train, y_train_log)

    return ridge_model, X_train


def extract_coefficients(model: object) -> pd.DataFrame:
    """
    Extract coefficients from the trained Ridge regression pipeline.
    """
    preprocessor = model.named_steps["preprocessor"]
    regressor = model.named_steps["model"]

    feature_names = preprocessor.get_feature_names_out()
    coefficients = regressor.coef_

    coefficients_df = pd.DataFrame(
        {
            "raw_feature_name": feature_names,
            "feature": [clean_feature_name(name) for name in feature_names],
            "feature_group": [infer_feature_group(name) for name in feature_names],
            "coefficient_log_scale": coefficients,
        }
    )

    coefficients_df["absolute_coefficient"] = (
        coefficients_df["coefficient_log_scale"].abs()
    )

    coefficients_df["approx_percent_effect"] = (
        np.expm1(coefficients_df["coefficient_log_scale"]) * 100
    )

    coefficients_df = coefficients_df.sort_values(
        "absolute_coefficient",
        ascending=False,
    ).reset_index(drop=True)

    return coefficients_df


def save_coefficients(coefficients_df: pd.DataFrame) -> None:
    """
    Save coefficient table.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    coefficients_df.to_csv(COEFFICIENTS_PATH, index=False)

    print("\nSaved coefficients")
    print("-" * 80)
    print(f"Coefficient table: {COEFFICIENTS_PATH}")


def save_coefficient_figures(coefficients_df: pd.DataFrame) -> None:
    """
    Save coefficient interpretation figures.
    """
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    sns.set_theme(style="whitegrid")

    top_positive = (
        coefficients_df
        .sort_values("coefficient_log_scale", ascending=False)
        .head(20)
        .copy()
    )

    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=top_positive,
        x="coefficient_log_scale",
        y="feature",
    )
    plt.title("Top 20 Positive Ridge Coefficients")
    plt.xlabel("Coefficient on Log Sale Price")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_positive_ridge_coefficients.png", dpi=300)
    plt.close()

    top_negative = (
        coefficients_df
        .sort_values("coefficient_log_scale", ascending=True)
        .head(20)
        .copy()
    )

    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=top_negative,
        x="coefficient_log_scale",
        y="feature",
    )
    plt.title("Top 20 Negative Ridge Coefficients")
    plt.xlabel("Coefficient on Log Sale Price")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_negative_ridge_coefficients.png", dpi=300)
    plt.close()

    top_absolute = coefficients_df.head(20).copy()

    plt.figure(figsize=(12, 8))
    sns.barplot(
        data=top_absolute,
        x="absolute_coefficient",
        y="feature",
    )
    plt.title("Top 20 Ridge Coefficients by Absolute Magnitude")
    plt.xlabel("Absolute Coefficient on Log Sale Price")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "top_absolute_ridge_coefficients.png", dpi=300)
    plt.close()

    print("\nSaved coefficient figures")
    print("-" * 80)
    print(f"Top positive: {FIGURES_DIR / 'top_positive_ridge_coefficients.png'}")
    print(f"Top negative: {FIGURES_DIR / 'top_negative_ridge_coefficients.png'}")
    print(f"Top absolute: {FIGURES_DIR / 'top_absolute_ridge_coefficients.png'}")


def print_interpretation_summary(coefficients_df: pd.DataFrame) -> None:
    """
    Print summary of strongest positive and negative associations.
    """
    print("=" * 80)
    print("RIDGE COEFFICIENT INTERPRETATION")
    print("=" * 80)

    print("\nImportant note")
    print(
        "Coefficients are estimated on log-transformed SalePrice. "
        "For scaled numeric features, coefficients represent the association "
        "of a one-standard-deviation increase with log price. "
        "For one-hot encoded categorical features, coefficients represent "
        "regularized associations, not causal effects."
    )

    print("\nTop 15 positive coefficients")
    print(
        coefficients_df
        .sort_values("coefficient_log_scale", ascending=False)
        .head(15)[
            [
                "feature",
                "feature_group",
                "coefficient_log_scale",
                "approx_percent_effect",
            ]
        ]
        .round(4)
    )

    print("\nTop 15 negative coefficients")
    print(
        coefficients_df
        .sort_values("coefficient_log_scale", ascending=True)
        .head(15)[
            [
                "feature",
                "feature_group",
                "coefficient_log_scale",
                "approx_percent_effect",
            ]
        ]
        .round(4)
    )


if __name__ == "__main__":
    interpretation_model, _ = train_interpretation_model()
    coefficients = extract_coefficients(interpretation_model)

    print_interpretation_summary(coefficients)
    save_coefficients(coefficients)
    save_coefficient_figures(coefficients)